# Cabal audit configuration for Good Vibes Scaner
# We ignore advisories that don't affect our usage patterns

[[ignore]]
id = "HSEC-2023-0007"  # readFloat memory exhaustion
reason = "We don't use Numeric.readFloat in our codebase"

[[ignore]]
id = "HSEC-2024-0003"  # process command injection on Windows
reason = "We only execute git commands, never .bat or .cmd files"