# HLint Configuration for Good Vibes Scaner ✨
# Keeping the code quality vibes high! 🚀

# Basic ignores for good vibes
- ignore: {name: "Use camelCase"}
- ignore: {name: "Redundant bracket"} 
- ignore: {name: "Unused LANGUAGE pragma"}
- ignore: {name: "Use newtype instead of data"}
- ignore: {name: "Use String instead of [Char]"}

# Encourage good patterns
- warn: {lhs: "map f (map g xs)", rhs: "map (f . g) xs"}
- warn: {lhs: "concat (map f xs)", rhs: "concatMap f xs"}
- warn: {lhs: "putStrLn (show x)", rhs: "print x"}
- hint: {lhs: "length xs > 0", rhs: "not (null xs)"}

# Discourage dangerous patterns  
- error: {lhs: "head xs", rhs: "listToMaybe xs"}
- error: {lhs: "tail xs", rhs: "drop 1 xs"}